-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Thu Apr 24 09:57:42 2008
--   Input Files:       model.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------

-- alter table service_type drop constraint service_type_fk_Maintenance_category_id-- (is implicitly done)
-- alter table scheduled_maintenance drop constraint scheduled_maintenance_fk_Service_type_id-- (is implicitly done)
-- alter table service_type drop constraint service_type_fk_Service_category_id-- (is implicitly done)
-- alter table scheduled_service drop constraint scheduled_service_fk_Calendar_id-- (is implicitly done)
-- alter table scheduled_service drop constraint scheduled_service_fk_Scheduled_maintenance_id-- (is implicitly done)
-- alter table xref_scheduled_service_server_list drop constraint xref_scheduled_service_server_list_fk_Scheduled_service_id-- (is implicitly done)
-- alter table times_available drop constraint times_available_fk_Calendar_id-- (is implicitly done)
-- alter table xref_scheduled_service_server_list drop constraint xref_scheduled_service_server_list_fk_Computer_number-- (is implicitly done)
-- alter table blocked_time drop constraint blocked_time_fk_Calendar_id-- (is implicitly done)


-- Generated Permissions Drops
-- --------------------------------------------------------------------




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------

drop table scheduled_maintenance cascade ;
drop table maintenance_category cascade ;
drop table calendar_selector cascade ;
drop table service_category cascade ;
drop table service_type cascade ;
drop table calendar cascade ;
drop table scheduled_service cascade ;
drop table xref_scheduled_service_server_list cascade ;
drop table times_available cascade ;
drop table user_cache cascade ;
drop table blocked_time cascade ;
drop table server_cache cascade ;
drop table change_log cascade ;


-- Generated SQL Schema
-- --------------------------------------------------------------------


-- scheduled_maintenance
create table scheduled_maintenance (
  id                        serial not null,
  master_ticket             text,	-- This references the ticket number.
  account_id                integer,	-- The account number (AccountNumber) of the associated account.
  account_name              text,
  state_id                  integer default 1,	-- Foreign key to the "state" table.
  date_assigned             timestamp with time zone default now(),
  additional_duration       interval,
  expedite                  boolean default false,
  general_description       text,
  service_type_id           integer,
  contact_id                integer,
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Scheduled_maintenance primary key (id)
) ;

-- maintenance_category
create table maintenance_category (
  id                        serial not null,
  name                      text,
  description               text,
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Maintenance_category primary key (id)
) ;

-- calendar_selector
-- Used to define what attributes of a scheduled maintenance object will
-- cause the selection of that calendar.
create table calendar_selector (
  id                        serial not null,
  calendar_id               integer,	-- Implicit reference to 'calendar' table.
  segment                   text,	-- stringified value of the account segment. Valid values are outputs from the 'segment' value from the CORE XMLRPC/Computer/getDetailsByComputer method.
  category                  integer,	-- implicit reference to the "maintenance_category" table
  server_os                 text,	-- Operating system
  datacenter                text,	-- Datacenter symbol
  has_managed_storage       boolean,	-- Set if managed storage is a factor. Null will mean that it does not matter.
  service_type_id           integer,	-- Implicit reference to the "service_type" table.
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Calendar_selector primary key (id)
) ;

-- service_category
create table service_category (
  id                        serial not null,
  name                      text,
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Service_category primary key (id)
) ;

-- service_type
-- The type of service that can be sch ... ades.
create table service_type (
  id                        serial not null,
  name                      text,
  description               text,
  active                    boolean default false,
  length                    interval,
  lead_time                 interval,
  service_category_id       integer,
  maintenance_category_id   integer,	-- Foreign key to the maintenance_category table.
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Service_type primary key (id)
) ;

-- calendar
-- A queue to collect upgrades.
create table calendar (
  id                        serial not null,
  name                      text,
  description               text,
  tckt_queue_id             integer,
  tckt_subcategory_id       integer,
  active                    boolean default true,
  bookings                  integer default 1,	-- Default value for bookings.
  timezone                  text default 'UTC',
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Calendar primary key (id)
) ;

-- scheduled_service
-- A scheduled upgrade service.
create table scheduled_service (
  id                        serial not null,
  description               text,
  ticket_number             text,
  start_time                timestamp with time zone,
  end_time                  timestamp with time zone,
  calendar_id               integer,
  scheduled_maintenance_id  integer,	-- Foreign key reference to the "UPGD_ScheduledMaintenance" table.
  state_id                  integer default 1,
  date_assigned             timestamp with time zone default now(),
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Scheduled_service primary key (id)
) ;

-- xref_scheduled_service_server_list
create table xref_scheduled_service_server_list (
  id                        serial not null,
  scheduled_service_id      integer,
  computer_number           integer,
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Xref_scheduled_service_server_list primary key (id)
) ;

-- times_available
create table times_available (
  id                        serial not null,
  calendar_id               integer,
  bookings                  integer,
  start_time                timestamp with time zone,
  end_time                  timestamp with time zone,
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Times_available primary key (id)
) ;

-- user_cache
create table user_cache (
  id                        integer not null,
  username                  text,
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_User_cache primary key (id)
) ;

-- blocked_time
-- Stores information about recurrence of times_available.
create table blocked_time (
  id                        serial not null,
  recurrence_id             integer,
  description               text,
  contact_id                integer,
  start_time                timestamp with time zone,
  end_time                  timestamp with time zone,
  bookings                  integer,
  date_assigned             timestamp with time zone default now(),
  calendar_id               integer,
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Blocked_time primary key (id)
) ;

-- server_cache
create table server_cache (
  id                        integer not null,
  name                      text,
  os_type                   text,
  datacenter_symbol         text,
  has_managed_storage       boolean default false,
  segment                   text,
  icon                      text,	-- The url of the icon in CORE for the device.
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Server_cache primary key (id)
) ;

-- change_log
create table change_log (
  id                        serial not null,
  table_id                  char(1),	-- Single character ID indicating the table reference. 't' : service_type; 'm' : scheduled_maintenance; 's' : scheduled_service
  row_id                    integer,
  contact                   text,
  date                      timestamp with time zone default now(),
  field                     text,
  old_value                 text,
  new_value                 text,
  creation_date             timestamp default now(),
  modification_date         timestamp default now(),
  constraint pk_Change_log primary key (id)
) ;
comment on column scheduled_maintenance.master_ticket is 'This references the ticket number.';
comment on column scheduled_maintenance.account_id is 'The account number (AccountNumber) of the associated account.';
comment on column scheduled_maintenance.state_id is 'Foreign key to the "state" table.';


comment on table calendar_selector is 'Used to define what attributes of a scheduled maintenance object will cause the selection of that calendar.';
comment on column calendar_selector.calendar_id is 'Implicit reference to \'calendar\' table.';
comment on column calendar_selector.segment is 'stringified value of the account segment. Valid values are outputs from the \'segment\' value from the CORE XMLRPC/Computer/getDetailsByComputer method.';
comment on column calendar_selector.category is 'implicit reference to the "maintenance_category" table';
comment on column calendar_selector.server_os is 'Operating system';
comment on column calendar_selector.datacenter is 'Datacenter symbol';
comment on column calendar_selector.has_managed_storage is 'Set if managed storage is a factor. Null will mean that it does not matter.';
comment on column calendar_selector.service_type_id is 'Implicit reference to the "service_type" table.';


comment on table service_type is 'The type of service that can be sch ... ades.';
comment on column service_type.maintenance_category_id is 'Foreign key to the maintenance_category table.';

comment on table calendar is 'A queue to collect upgrades.';
comment on column calendar.bookings is 'Default value for bookings.';

comment on table scheduled_service is 'A scheduled upgrade service.';
comment on column scheduled_service.scheduled_maintenance_id is 'Foreign key reference to the "UPGD_ScheduledMaintenance" table.';




comment on table blocked_time is 'Stores information about recurrence of times_available.';

comment on column server_cache.icon is 'The url of the icon in CORE for the device.';

comment on column change_log.table_id is 'Single character ID indicating the table reference. \'t\' : service_type; \'m\' : scheduled_maintenance; \'s\' : scheduled_service';



-- Generated SQL Views
-- --------------------------------------------------------------------




-- Generated Permissions
-- --------------------------------------------------------------------



-- Generated SQL Insert statements
-- --------------------------------------------------------------------



-- Generated SQL Constraints
-- --------------------------------------------------------------------

alter table service_type add constraint service_type_fk_Maintenance_category_id
  foreign key (maintenance_category_id)
  references maintenance_category (id)  ;
alter table scheduled_maintenance add constraint scheduled_maintenance_fk_Service_type_id
  foreign key (service_type_id)
  references service_type (id)  ;
alter table service_type add constraint service_type_fk_Service_category_id
  foreign key (service_category_id)
  references service_category (id)  ;
alter table scheduled_service add constraint scheduled_service_fk_Calendar_id
  foreign key (calendar_id)
  references calendar (id)  ;
alter table scheduled_service add constraint scheduled_service_fk_Scheduled_maintenance_id
  foreign key (scheduled_maintenance_id)
  references scheduled_maintenance (id)  ;
alter table xref_scheduled_service_server_list add constraint xref_scheduled_service_server_list_fk_Scheduled_service_id
  foreign key (scheduled_service_id)
  references scheduled_service (id)  ;
alter table times_available add constraint times_available_fk_Calendar_id
  foreign key (calendar_id)
  references calendar (id)  ;
alter table xref_scheduled_service_server_list add constraint xref_scheduled_service_server_list_fk_Computer_number
  foreign key (computer_number)
  references server_cache (id)  ;
alter table blocked_time add constraint blocked_time_fk_Calendar_id
  foreign key (calendar_id)
  references calendar (id)  ;

