-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Wed Dec 19 17:36:57 2007
--   Input Files:       model.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------

-- alter table qcmc_val_service_type drop constraint qcmc_val_service_type_fk_Maintenance_category_id-- (is implicitly done)
-- alter table qcmc_scheduled_maintenance drop constraint qcmc_scheduled_maintenance_fk_Service_type_id-- (is implicitly done)
-- alter table qcmc_xref_scheduled_maintenance_server_list drop constraint qcmc_xrf_schdld_mntnc_srvr_lst_fk_Scheduled_maintenance_id-- (is implicitly done)
-- alter table qcmc_val_service_type drop constraint qcmc_val_service_type_fk_Service_category_id-- (is implicitly done)
-- alter table qcmc_scheduled_service drop constraint qcmc_scheduled_service_fk_Calendar_id-- (is implicitly done)
-- alter table qcmc_scheduled_service drop constraint qcmc_scheduled_service_fk_Scheduled_maintenance_id-- (is implicitly done)
-- alter table qcmc_xref_scheduled_service_computer drop constraint qcmc_xref_scheduled_service_computer_fk_Scheduled_service_id-- (is implicitly done)
-- alter table qcmc_log_completion drop constraint qcmc_log_completion_fk_Scheduled_service_id-- (is implicitly done)
-- alter table qcmc_calendar_blocked_times drop constraint qcmc_calendar_blocked_times_fk_Calendar_id-- (is implicitly done)


-- Generated Permissions Drops
-- --------------------------------------------------------------------




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------

--drop table qcmc_scheduled_maintenance cascade ;
--drop table qcmc_val_maintenance_category cascade ;
--drop table qcmc_scheduled_maintenance_maintenance_calendar_selector cascade ;
--drop table qcmc_val_service_category cascade ;
--drop table qcmc_val_service_type cascade ;
--drop table qcmc_xref_scheduled_maintenance_server_list cascade ;
--drop table qcmc_calendar cascade ;
--drop table qcmc_scheduled_service cascade ;
--drop table qcmc_log_completion cascade ;
--drop table qcmc_xref_scheduled_service_computer cascade ;
--drop table qcmc_calendar_blocked_times cascade ;
--drop table qcmc_user_cache cascade ;


-- Generated SQL Schema
-- --------------------------------------------------------------------


-- qcmc_scheduled_maintenance
create table qcmc_scheduled_maintenance (
  id                        serial not null,
  master_ticket             integer not null,	-- This references the ticket ID, not the ticket ref. no. We need the not null constraint, but we cannot provide a default, because that would not make sense.
  state                     integer default 1,	-- Foreign key to the "state" table.
  service_type_id           integer,
  expedite                  text,
  additional_duration       interval,
  general_description       text,
  billing_text              text,
  employee_contact          integer,
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_scheduled_maintenance primary key (id)
) ;

-- qcmc_val_maintenance_category
create table qcmc_val_maintenance_category (
  id                        serial not null,
  name                      text,
  description               text,
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_val_maintenance_category primary key (id)
) ;

-- qcmc_scheduled_maintenance_maintenance_calendar_selector
-- Used to define what attributes of a scheduled maintenance object will
-- cause the selection of that calendar.
create table qcmc_scheduled_maintenance_maintenance_calendar_selector (
  id                        serial not null,
  calendar                  integer,	-- Foreign key reference to "UPGD_Queue"
  segment                   integer,	-- Foreign key reference to "ACCT_val_AccountType"
  category                  integer,	-- reference to the "maintenance_category" table
  server_os                 integer,	-- reference to the "COMP_val_OSGroup" table.
  datacenter                integer,	-- Reference to the "datacenter" table.
  service_type              integer,	-- Reference to the "service_type" table.
  sku                       integer,	-- reference to the "sku" table.
  constraint pk_Qcmc_scheduled_maintenance_maintenance_calendar_selector primary key (id)
) ;

-- qcmc_val_service_category
create table qcmc_val_service_category (
  id                        serial not null,
  name                      text,
  description               text,
  active                    boolean default false,
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_val_service_category primary key (id)
) ;

-- qcmc_val_service_type
-- The type of service that can be sch ... ades.
create table qcmc_val_service_type (
  id                        serial not null,
  name                      text,
  description               text,
  active                    boolean default false,
  service_category_id       integer,
  maintenance_category_id   integer,	-- Foreign key to the maintenance_category table.
  length                    interval,
  lead_time                 interval,
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_val_service_type primary key (id)
) ;

-- qcmc_xref_scheduled_maintenance_server_list
create table qcmc_xref_scheduled_maintenance_server_list (
  id                        serial not null,
  scheduled_maintenance_id  integer,	-- Reference to scheduled_maintenance object.
  computer                  integer,
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_xref_scheduled_maintenance_server_list primary key (id)
) ;

-- qcmc_calendar
-- A queue to collect upgrades.
create table qcmc_calendar (
  id                        serial not null,
  name                      text,
  description               text,
  TCKT_QueueID              integer,
  active                    boolean default true,
  max_bookings              integer default 1,
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_calendar primary key (id)
) ;

-- qcmc_scheduled_service
-- A scheduled upgrade service.
create table qcmc_scheduled_service (
  id                        serial not null,
  service_type              integer,
  description               text,
  date_assigned             date,-- default now(),
  ticket                    integer,
  start_time                timestamp with time zone,
  end_time                  timestamp with time zone,
  special_instructions      text,
  contact_id                integer,
  calendar_id               integer,
  scheduled_maintenance_id  integer,	-- Foreign key reference to the "UPGD_ScheduledMaintenance" table.
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_scheduled_service primary key (id)
) ;

-- qcmc_log_completion
-- A log of when upgrade services were ... eted.
create table qcmc_log_completion (
  id                        serial not null,
  scheduled_service_id      integer,
  contact_id                integer,
  date                      timestamp with time zone,
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_log_completion primary key (id)
) ;

-- qcmc_xref_scheduled_service_computer
create table qcmc_xref_scheduled_service_computer (
  id                        serial not null,
  scheduled_service_id      integer,
  computer_number           integer,
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_xref_scheduled_service_computer primary key (id)
) ;

-- qcmc_calendar_blocked_times
create table qcmc_calendar_blocked_times (
  id                        serial not null,
  calendar_id               integer,
  start_time                timestamp with time zone,
  end_time                  timestamp with time zone,
  creation_date             timestamp,-- default now(),
  modification_date         timestamp,-- default now(),
  constraint pk_Qcmc_calendar_blocked_times primary key (id)
) ;

-- qcmc_user_cache
create table qcmc_user_cache (
  contact_id                integer not null,
  first_name                text,
  last_name                 text,
  username                  text,
  constraint pk_Qcmc_user_cache primary key (contact_id)
) ;
--comment on column qcmc_scheduled_maintenance.master_ticket is 'This references the ticket ID, not the ticket ref. no. We need the not null constraint, but we cannot provide a default, because that would not make sense.';
--comment on column qcmc_scheduled_maintenance.state is 'Foreign key to the "state" table.';
--
--
--comment on table qcmc_scheduled_maintenance_maintenance_calendar_selector is 'Used to define what attributes of a scheduled maintenance object will cause the selection of that calendar.';
--comment on column qcmc_scheduled_maintenance_maintenance_calendar_selector.calendar is 'Foreign key reference to "UPGD_Queue"';
--comment on column qcmc_scheduled_maintenance_maintenance_calendar_selector.segment is 'Foreign key reference to "ACCT_val_AccountType"';
--comment on column qcmc_scheduled_maintenance_maintenance_calendar_selector.category is 'reference to the "maintenance_category" table';
--comment on column qcmc_scheduled_maintenance_maintenance_calendar_selector.server_os is 'reference to the "COMP_val_OSGroup" table.';
--comment on column qcmc_scheduled_maintenance_maintenance_calendar_selector.datacenter is 'Reference to the "datacenter" table.';
--comment on column qcmc_scheduled_maintenance_maintenance_calendar_selector.service_type is 'Reference to the "service_type" table.';
--comment on column qcmc_scheduled_maintenance_maintenance_calendar_selector.sku is 'reference to the "sku" table.';
--
--
--comment on table qcmc_val_service_type is 'The type of service that can be sch ... ades.';
--comment on column qcmc_val_service_type.maintenance_category_id is 'Foreign key to the maintenance_category table.';
--
--comment on column qcmc_xref_scheduled_maintenance_server_list.scheduled_maintenance_id is 'Reference to scheduled_maintenance object.';
--
--comment on table qcmc_calendar is 'A queue to collect upgrades.';
--
--comment on table qcmc_scheduled_service is 'A scheduled upgrade service.';
--comment on column qcmc_scheduled_service.scheduled_maintenance_id is 'Foreign key reference to the "UPGD_ScheduledMaintenance" table.';
--
--comment on table qcmc_log_completion is 'A log of when upgrade services were ... eted.';






-- Generated SQL Views
-- --------------------------------------------------------------------




-- Generated Permissions
-- --------------------------------------------------------------------



-- Generated SQL Insert statements
-- --------------------------------------------------------------------



-- Generated SQL Constraints
-- --------------------------------------------------------------------

--alter table qcmc_val_service_type add constraint qcmc_val_service_type_fk_Maintenance_category_id
--  foreign key (maintenance_category_id)
--  references qcmc_val_maintenance_category (id)  ;
--alter table qcmc_scheduled_maintenance add constraint qcmc_scheduled_maintenance_fk_Service_type_id
--  foreign key (service_type_id)
--  references qcmc_val_service_type (id)  ;
--alter table qcmc_xref_scheduled_maintenance_server_list add constraint qcmc_xrf_schdld_mntnc_srvr_lst_fk_Scheduled_maintenance_id
--  foreign key (scheduled_maintenance_id)
--  references qcmc_scheduled_maintenance (id)  ;
--alter table qcmc_val_service_type add constraint qcmc_val_service_type_fk_Service_category_id
--  foreign key (service_category_id)
--  references qcmc_val_service_category (id)  ;
--alter table qcmc_scheduled_service add constraint qcmc_scheduled_service_fk_Calendar_id
--  foreign key (calendar_id)
--  references qcmc_calendar (id)  ;
--alter table qcmc_scheduled_service add constraint qcmc_scheduled_service_fk_Scheduled_maintenance_id
--  foreign key (scheduled_maintenance_id)
--  references qcmc_scheduled_maintenance (id)  ;
--alter table qcmc_xref_scheduled_service_computer add constraint qcmc_xref_scheduled_service_computer_fk_Scheduled_service_id
--  foreign key (scheduled_service_id)
--  references qcmc_scheduled_service (id)  ;
--alter table qcmc_log_completion add constraint qcmc_log_completion_fk_Scheduled_service_id
--  foreign key (scheduled_service_id)
--  references qcmc_scheduled_service (id)  ;
--alter table qcmc_calendar_blocked_times add constraint qcmc_calendar_blocked_times_fk_Calendar_id
--  foreign key (calendar_id)
--  references qcmc_calendar (id)  ;

